const NotificationType = Object.freeze({
    PAYMENT_MADE_FOR_PLAN: "PAYMENT_MADE_FOR_PLAN",
    PRODUCT_ACCESS: "PRODUCT_ACCESS",
    TENANT_CREATED: "TENANT_CREATED",
    TENANT_DEACTIVATED: "TENANT_DEACTIVATED",
    PLAN_CREATED: "PLAN_CREATED",
    PLAN_DEACTIVATED: "PLAN_DEACTIVATED",
    PLAN_DELETED: "PLAN_DELETED",
    SUBSCRIPTION_PAUSED: "SUBSCRIPTION_PAUSED",
    SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",
    SUBSCRIPTION_AUTO_RENEWED: "SUBSCRIPTION_AUTO_RENEWED",
    ISSUE_SUBMITTED: "ISSUE_SUBMITTED",
    ISSUE_ASSIGNED: "ISSUE_ASSIGNED",
    ISSUE_ASSIGNED_ADMIN: "ISSUE_ASSIGNED_ADMIN",
    ISSUE_IN_PROGRESS: "ISSUE_IN_PROGRESS",
    ISSUE_REASSIGNED: "ISSUE_REASSIGNED",
    ISSUE_PRIORITY_CHANGED: "ISSUE_PRIORITY_CHANGED",
    ISSUE_CATEGORY_CHANGED: "ISSUE_CATEGORY_CHANGED",
    ISSUE_RESOLVED: "ISSUE_RESOLVED",
});

const NotificationEntityType = Object.freeze({
    APPOINTMENT: "APPOINTMENT",
    ISSUE: "ISSUE",
    SUBSCRIPTION: "SUBSCRIPTION",
    INVOICE: "INVOICE",
    PAYMENT: "PAYMENT",
    TENANT: "TENANT",
    PLAN: "PLAN",
});

export { NotificationEntityType, NotificationType };
